apiVersion: v1
kind: Service
metadata:
  name: customers-service
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8086
      targetPort: 8086
    - name: grpc
      port: 9090
      targetPort: 9090
  selector:
    app: customers-service