apiVersion: v1
kind: Service
metadata:
  name: mediator
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8087
      targetPort: 8087
    - name: grpc
      port: 9091
      targetPort: 9091
  selector:
    app: mediator