apiVersion: v1
kind: Service
metadata:
  name: sellers-service
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8089
      targetPort: 8089
    - name: grpc
      port: 9093
      targetPort: 9093
  selector:
    app: sellers-service